directory:
  - .
quiet: true
skip-check:
  - CKV_AWS_24
  - CKV_AWS_79
  - CKV_AWS_126
  - CKV_AWS_130
  - CKV_AWS_135
  - CKV_AWS_260
  - CKV2_AWS_11
  - CKV2_AWS_12
  - CKV2_AWS_41
skip-path:
  - .terraform
  - volume
