global:
  scrape_interval: 30s
  evaluation_interval: 30s
rule_files:
  - "alert_rules.yml"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "liav-web-server"
    static_configs:
      - targets: ["host.docker.internal:30081"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093