name: "Terraform CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Quality Gates"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Checkov
        run: pip install checkov

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false -input=false

      - name: TFLint Init
        run: tflint --init

      - name: TFLint
        run: tflint --recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Checkov
        run: checkov -d . --config-file .checkov.yml
